### ISSUE TITLE
ictreg.joint giving "log-likelihood is not monotonically increasing" error

### ISSUE THREAD

**Issue by soominoh1** [SensitiveQuestions/list#18]
I'm trying to use "ictreg.joint" function, but I get this error:

`Error in if (llik.const < pllik.const) warning("log-likelihood is not monotonically increasing.") : missing value where TRUE/FALSE needed  
`

I have tried dropping NAs, converting to tibble, etc but still get the error. I have checked the "class" of all the variables, and they are in the integers, the same class as the variables in the Mexico dataset. I have also tried using other list experiment replication datasets, and got the same error. Have you encountered this error before and if so, would you kindly be able to help?

Thank you!

**Comment by kosukeimai** [comment]
This means that the EM algorithm isn't quite working well.  This happens for example when there are very few responses in some categories.  You may want to try nonlinear least squares approach by setting `method = "nls"`.  You could also try an overdispersed model by setting `overdispersed = TRUE`
